#!/bin/bash


# Start the service
start() 
{
      echo "START"
}

# Stop the service
stop() 
{
      echo "STOP"
}

# Stop the service
status() 
{
      echo "STATUS"
}


### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
