#!/bin/bash
#
#
# Get function from functions library
. /etc/init.d/functions
# Start the service FOO
start() {
      echo "START"
}
# Restart the service FOO
stop() {
      echo "STOP"
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
